EmptyLinesAroundBlockBody:
  Enabled: false
Documentation:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
<<<<<<< HEAD
Style/StringLiterals:
  Enabled: false
=======
>>>>>>> 596954af958e6a8e8a7a3a654ef5e5530983f27d
