EmptyLinesAroundBlockBody:
  Enabled: false
Documentation:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
StringLiterals:
  Enabled: false
StringLiteralsInInterpolation:
  Enabled: false
