require "./airport.rb"

puts "#{frankfurt = Airport.new}"
puts "#{boeing = Plane.new}"
puts "#{mig = Plane.new}"
puts "#{spitfire = Plane.new}"
puts "#{airbus = Plane.new}"

puts "we are asking #{boeing} to land at #{frankfurt}"
puts "#{frankfurt.land(boeing)}"
puts "there are now #{frankfurt.planes.count} planes at Frankfurt Airport"
puts "we are asking #{mig} to land at #{frankfurt}"
puts "#{frankfurt.land(mig)}"
puts "there are now #{frankfurt.planes.count} planes at Frankfurt Airport"
#puts "as an edge case we are asking #{mig} to land again"
#puts "#{frankfurt.land(mig)}"
#puts "we are asking #{spitfire} to take off although it is airborne"
#puts "#{frankfurt.take_off(spitfire)}"
puts "we are asking #{boeing} to take off again"
puts "#{frankfurt.take_off(boeing)}"
puts "there are now #{frankfurt.planes.count} planes at Frankfurt Airport"
#puts "we are asking ten planes to land althoug remaining capacity is only 9"
#puts "#{10.times do frankfurt.land(Plane.new)end}"
